# Workflows piece together jobs, and jobs piece together steps. We'll now create a job that runs an action.
# Actions can be used from within the same repository, from any other public repository, or from a published Docker container image.

name: A workflow for my Hello World file

on: push

jobs:
  build:
    name: Hello world action
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: ./action-a
        with:
          MY_NAME: "Arthur"
